function gscr_cozinha(){
    enum ALTERACOES_RECEITA {
        SEM_ALTERACAO,
        TROCAR_QTD,
        ACRESC_INGREDIENTE,
        REMOVER_INGREDIENTE,
    }
    enum SABORES_BOLO {
        LARANJA,
        BAUNILHA,
        CHOCOLATE,
		LARANJASEMGLUTEN,
        BAUNILHASEMGLUTEN,
        CHOCOLATESEMGLUTEM,
		LARANJAVEGETAL,
        BAUNILHAVEGETAL,
        CHOCOLATEVEGETAL,
    }
}